
helpText = {'1: Select h-maximum height parameter for adjustment  (smaller values to compensate under-segmentation, larger values compensate over-segmentation, only works in watershed mode)', ...
            '2: Select Minimum Area feature threshold (objects with smaller area will be discarded)', ...
            '3: Select Eccenticity feature threshold (the closer to 0, the more the objects need no be circular)', ...
            '4: Select Minimum Intensity feature threshold (increase to suppress detections in background regions)', ...
            'CTRL + Shift + Left Button: Delete manual selection marker closest to the cursor', ...
            'CTRL + Left Button: Select detection at the cursor position (overrides feature thresholds)', ...
            'Shift + Left Button: Deselect detection at the cursor position', ...
            'Left Arrow: Load previous image', ...
            'Right Arrow: Load next image', ...
            '-/+: Decrease/increase the currently selected parameter/threshold', ...
            'A: Perform automatic seed detection upon parameter change (updates instantly but may be slowing down)', ...
            'B: Show brightfield channel', ...
            'C: Switch circle detection mode (watershed / hough)', ...
            'E: Export all results and generate SciXMiner projects for tracking', ...
            'F: Show fluorescence channel', ...
            'H: Show this help dialog', ...
            'P: Change parameters for the Hough transform', ...
            'V: Toggle visibility of the parameters on top left corner', ...
            'W: Show watershed segmentation image', ...
            '', ...
            'Hint: In case key presses show no effect, left click once on the image and try hitting the button again. This only happens if the window looses the focus. Segmentation results using the current parameters/thresholds can be automatically generated for all images by pressing "E".'};

helpdlg(helpText);